name: Build OCI-image using build packs

on:
  push:
    branches: ["main"]
    paths:
      - "!.github/workflows/**"
      - ".github/workflows/test-buildpack.yml"
env:
  EVOAR_URI: buildpacks.cr.cloud.ru
  IMAGE_NAME: heroku-nodejs
  MSFT_BUILDER: mcr.microsoft.com/oryx/builder:debian-bullseye-20240124.1
  PACKETO_BUILDER: paketobuildpacks/builder-jammy-full
  HEROKU_BUILDER: heroku/builder:22
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install pack CLI
        shell: bash
        run: (curl -sSL "https://github.com/buildpacks/pack/releases/download/v0.33.2/pack-v0.33.2-${{ runner.os }}.tgz" | sudo tar -C /usr/local/bin/ --no-same-owner -xzv pack)

      - name: Create runnable application image using builder
        id: buildpack
        shell: bash
        run: |
          echo 'Attempting to enable experimental features for the pack CLI'
          pack config experimental true

          pack build \
           ${{ env.EVOAR_URI }}/${{ env.IMAGE_NAME }}:build${{ github.sha }} \
            --path nodejs \
            --builder ${{env.HEROKU_BUILDER}} \

      - name: Log in to Evolution Artifact Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.EVOAR_URI }}
          username: ${{ secrets.EVOAR_KEYID }}
          password: ${{ secrets.EVOAR_KEYSECRET }}

      - name: Pushing to registry using Docker
        shell: bash
        run: |
          docker push ${{ env.EVOAR_URI }}/${{ env.IMAGE_NAME }}:build${{ github.sha }}
